### ISSUE TITLE
thinkpad-rotate.py problems

### ISSUE THREAD

**Issue by rexcze-zz** [rexcze/thinkpad-yoga-12-scripts#1]
# thinkpad-rotate.py

unable to find device SYNAPTICS Synaptics Touch Digitizer V04
Traceback (most recent call last):
  File "./thinkpad-rotate.py", line 114, in <module>
    rotate(i)
  File "./thinkpad-rotate.py", line 84, in rotate
    ] + s['coord'].split(),env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['xinput', 'set-prop', 'SYNAPTICS Synaptics Touch Digitizer V04', 'Coordinate Transformation Matrix', '0', '1', '0', '-1', '0', '1', '0', '0', '1']' returned non-zero exit status 1

**Comment by rexcze-zz** [comment]
This problem occurs because "SYNAPTICS Synaptics Touch Digitizer V04" device disappear for some time during screen rotation
